### ISSUE TITLE
Update to CEDS emissions

### ISSUE THREAD

**Issue by chrisroadmap** [openclimatedata/ceds#2]
It looks like CEDS are updating their emissions and also running to 2019:

https://github.com/JGCRI/CEDS

Any plans to include this update?

**Comment by rgieseke** [comment]
Yes, as they are still using the wide 'x2000' format, having this pre-processed should be useful. It seems it's a pre-release atm, do you have an urgent use case?

Maybe the `process.py` script works without much changing.

**Comment by rgieseke** [comment]
CEDS v_2020_09_11 Pre-Release Emission Data

https://zenodo.org/record/4025316

**Comment by chrisroadmap** [comment]
I originally thought the data wasn't available, then saw the Zenodo link myself...

It's useful to update the historical forcing up to 2019, but I can work from these raw datasets from Zenodo.

**Comment by rgieseke** [comment]
Updated!
Both versions are now here: https://github.com/openclimatedata/ceds/tree/master/data
